### ISSUE TITLE
"queer" should not be flagged as a "bad word"

### ISSUE THREAD

**Issue by cvan** [mozilla/addons-linter#1885] opened 2018-03-07 08:49 UTC
`queer` should be not flagged as a ["bad word"](https://github.com/mozilla/addons-linter/blob/master/src/badwords.json#L265).

Though context is definitely important, `queer` on its own is a common LGBT* term used colloquially, professionally, and appropriately without derogation.

**Comment by jvillalobos** [comment] 2018-03-07 14:50
Duplicate of https://github.com/mozilla/addons-linter/issues/1851

**Closed by jvillalobos** 2018-03-07 14:50 UTC
