### ISSUE TITLE
"String name contains invalid characters" error should be more helpful

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-linter#1872] opened 2018-02-28 16:36 UTC
Originally filed at https://github.com/mozilla/addons/issues/650 by @arantius

-------

I just tried to upload a new version of my extension.  I got the error

> String name contains invalid characters
> Error: String name should only contain alpha-numeric characters, _ and @ (https://mzl.la/2Eztyi5).

140 times.  Each was tagged with the file it came from, but not which name triggered it.  It's a lot of effort for me to figure out which name it might be complaining about, to try and fix it.  It's a lot less effort for it to just TELL me which name it doesn't like.

(Also: WHY?  Why do you care which strings I use for my strings' names?  They definitely work, as is now, in my source...)

See also greasemonkey/greasemonkey#2862

**Comment by freaktechnik** [comment] 2018-03-09 13:22
As I originally implemented that: sadly the linter doesn't support lines or similar for JSON files, only paths, which would already be sufficient here.

I assume this is a rule originally from Chrome, which Firefox doesn't seem to actually enforce. I asked if this specific rule should possibly be degraded to a warning about compatibility instead, but didn't get any feedback.

**Comment by Marat-Tanalin** [comment] 2018-03-12 18:57
Can’t upload my new addon version due to this uninformative error multiple times.

I _suspect_ the issue is with a dot in string name. But in fact the previous version of my extension as well as other two extension do work like a charm, so dots should probably be allowed back.

Linter should not formally disallow something that actually works and worked always.

**Comment by freaktechnik** [comment] 2018-03-27 21:59
This error has been removed, see #1918

**Comment by EnTeQuAk** [comment] 2018-06-21 07:48
Closing since this has been fixed.

**Closed by EnTeQuAk** 2018-06-21 07:48 UTC
Labels: triaged
