### ISSUE TITLE
The extension submission fails

### ISSUE THREAD

**Issue by kvetko** [mozilla/addons-linter#1915] opened 2018-03-16 10:26 UTC
### Describe the problem and steps to reproduce it:
We can't publish our extension to the store. 

We use background script shared between FF and Chrome. Our background script references js files in 
following way:
`chrome.tabs.executeScript(
                sender.tab.id,
                { file: "js/dialog.js", runAt: "document_idle" }
            );`

### What happened?
When we submit our extension zip file for validation and signing to Mozilla we are getting following error:
<img width="1014" alt="screen shot 2018-03-16 at 07 01 47" src="https://user-images.githubusercontent.com/37440134/37515852-78fb5ee0-290c-11e8-8a5b-379f1204a01a.png">

### What did you expect to happen?
Submission passes we didn't change anything relevant in the script from last successful submission

### Anything else we should know?
The issue seems to me caused by fix of #1803
If linter is being used in FF  itself to check extension fitness in runtime then IMHO all extensions using similar folder structure as we do won't load in FF59 
The extension we are trying to upload is following:
[pam.zip](https://github.com/mozilla/addons-linter/files/1818840/pam.zip)

**Comment by wagnerand** [comment] 2018-03-16 10:31
@EnTeQuAk given the repeated regressions with this rule, I'd be in favor to disable it until we have proper tests and make sure we don't regress anymore. Thoughts?

**Comment by pardeepshokeen** [comment] 2018-03-16 13:03
hi. The reason for this problem is how path to file is resolved 
As written in [executeScript docs](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/executeScript) 

> file Optional
string. Path to a file containing the code to inject. In Firefox, relative URLs are resolved relative to the current page URL. In Chrome, these URLs are resolved relative to the extension's base URL. To work cross-browser, you can specify the path as an absolute URL, starting at the extension's root, like this: "/path/to/script.js".

so it resolved differently in chrome and firefox

**Comment by kvetko** [comment] 2018-03-16 13:36
@pardeepshokeen thanks for this. We were able resolve the issue by changing our paths to absolute. Keeping this open as I still believe that this is regression and should be addressed.

**Comment by EnTeQuAk** [comment] 2018-03-19 13:41
@wagnerand 

> @EnTeQuAk given the repeated regressions with this rule, I'd be in favor to disable it until we have proper tests and make sure we don't regress anymore. Thoughts?

Or degrade it to a warning severity?

**Comment by EnTeQuAk** [comment] 2018-03-21 13:31
This should have been fixed in https://github.com/mozilla/addons-linter/pull/1923 and will land this Thursday

**Closed by EnTeQuAk** 2018-03-21 13:31 UTC
Labels: component: rule, priority: p3, triaged

**Comment by vcarciu** [comment] 2018-03-21 15:10
Verified with extension from description and no content script error is displayed. 
Anyway, based on the fact that the extension from description will return a ""update_url" is not allowed" error I think that the extension is not exactly the same one used in reporter's description.
I will mark this as verified based on the other similar issues where the examples were good (ie. https://github.com/mozilla/addons-linter/issues/1920)
