### ISSUE TITLE
wrong "validation error": JavaScript syntax error in class

### ISSUE THREAD

**Issue by YuiCC** [mozilla/addons-linter#3549] opened 2021-01-21 09:29 UTC
# addon upload Validation get a syntax error in JavaScript class which running normal in firefox addon debug mode

![image](https://user-images.githubusercontent.com/21233545/105330430-3b0d7500-5c0d-11eb-833f-d338b58d8618.png)
![image](https://user-images.githubusercontent.com/21233545/105331200-24b3e900-5c0e-11eb-86d4-4bce5bccf501.png)

**Comment by Rob--W** [comment] 2021-01-21 09:34
The shown screenshot of the code looks fine (it's an instance field). Does your class contain a static field? The linter doesn't support that yet - https://github.com/mozilla/addons-linter/issues/3062

**Comment by YuiCC** [comment] 2021-01-21 09:46
that class does not contain any static field.  And that code validate successful in chrome webstore

**Comment by Rob--W** [comment] 2021-01-21 10:01
Could you share the whole file?

**Comment by YuiCC** [comment] 2021-01-21 14:46
the file : https://github.com/YuiCC/CSS-Tab/blob/master/units/StringUnits.js

**Comment by Rob--W** [comment] 2021-01-22 13:32
I see. It's not just static fields, instance fields are not supported by eslint (and thus `addons-linter`) either - https://github.com/mozilla/addons-linter/issues/3062#issuecomment-714390218

So this issue is a duplicate of #3062

**Closed by Rob--W** 2021-01-22 13:32 UTC
