### ISSUE TITLE
Javascript syntax error in review process

### ISSUE THREAD

**Issue by Mephiles** [mozilla/addons-linter#3189] opened 2020-05-28 11:41 UTC
### Describe the problem and steps to reproduce it:
I uploaded a new version of my browser extension/addon. It dind't pass because there was an error on line 2 (line 2: "import data from "../other_script.js";"). This had passed before so I figured this wasn't the actual problem. 

After commenting line 2 out and resubmitting the new version, it came out that the real reason was line 342 which had "await function_name()" and it's parent function wasn't assigned as "async function".

**Comment by jvillalobos** [comment] 2020-05-28 17:39
Possibly related to https://github.com/mozilla/addons-linter/issues/2498 and other issues around JS syntax.

**Comment by willdurand** [comment] 2020-06-23 14:36
@Mephiles hey, would you be able to share the file content? It's tricky to understand what the problem is.

**Comment by Mephiles** [comment] 2020-06-23 14:39
Well there is not much to add. The file can be found at https://github.com/Mephiles/torntools_extension/blob/master/torntools/background.js

It starts with an import statement and somewhere deep in the code there was an "await" keyword in a function that was not set as "async". The point is that a normal browser running it understands that there is an unexpected keyword but Firefox code check flagged the import statement as an error. Removing the import statement revealed the actual error by the Firefox code check.

**Comment by willdurand** [comment] 2020-06-23 14:40
> Well there is not much to add. The file can be found at [Mephiles/torntools_extension:torntools/background.js@`master`](https://github.com/Mephiles/torntools_extension/blob/master/torntools/background.js?rgh-link-date=2020-06-23T14%3A39%3A48Z)

The link to the code is useful, thanks :)

**Comment by willdurand** [comment] 2020-06-23 14:47
> Removing the import statement revealed the actual error by the Firefox code check.

ha ok, so I am not sure if we can do anything really. I guess the parser was confused by the other error but not sure we can do anything about that. Closing for now as it does not seem to be a bug with addons-linter.

Thanks!

**Closed by willdurand** 2020-06-23 14:47 UTC
Labels: needs: info
