### ISSUE TITLE
AMO addon updater errors out - although Firefox 61 does not

### ISSUE THREAD

**Issue by JohnLeicht** [mozilla/addons-linter#2101] opened 2018-07-11 14:01 UTC
### Describe the problem and steps to reproduce it:
[BH-18.7.11.275.zip](https://github.com/mozilla/addons-linter/files/2184728/BH-18.7.11.275.zip)

(Please include as many details as possible.)
When unzipped, the attached file tests fine in Firefox 61 (I am not using Developer or Nightly). The upload should be accepted by AMO; however, it indicates there are 15-errors. Each error points to the 1st import statement in each .js file.

There are no errors in my Firefox 61 testing - the AMO linter is not properly recognizing my imports even though my addon works fine in Firefox 61!!!

### Anything else we should know?
(Please include screenshots and any relevant files.)

**Comment by wagnerand** [comment] 2018-07-11 14:43
Duplicate of #1775.

**Closed by wagnerand** 2018-07-11 14:43 UTC

**Comment by EnTeQuAk** [comment] 2018-07-12 07:13
It is a duplicate of #1775 which hasn't been fixed yet. We're working on getting es6 module support in the linter as soon as possible to not block submissions any longer.
