### ISSUE TITLE
Static theme linter does not identify errors when some properties/values are missing

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-linter#1913] opened 2018-03-15 15:28 UTC
Follow up for #1587 

STR:
1. Submit a static theme and modify it's manifest to force some errors in the linter
2. Observe the erros idnetified during validation

Expected result:
Errors are detected when certain properties/values are missing or wrongly defined

Actual result:
The following items are not properly handled:
 1. the linter detects no errors when certain properties are misspelled, for example:` theme, headerURL, additional_backgrounds, colors, accentcolor, textcolor `etc. - all these can be misspelled
 2.  missing `headerURL `- the linter does not detect it - after clicking on 'Continue" an internal server error is generated
 3. no error detected when an image is missing its extension, i.e.` .png`, `.svg` -> internal server error generated after clicking Continue
 4. no error detected when `additional_backgrounds` are defined but there is no `additional_backgrounds_alignment` property included or when `additional_backgrounds_alignment` does not specify a value for all the defined backgrounds
 5. `accentcolor` and `textcolor` - no error when value is an empty string ie. ` ""` or when they contain a wrong color value (i.e. any value is accepted, like `dje757$%#`, `4`)
 6. when an image defined in the manifest is missing from the package - no error detected in the linter - after clicking on 'Continue" an internal server error is generated (similar to point 3)

@EnTeQuAk please have a look at this list and comment on what is expected/pit of scope/actual error etc.
Thanks.

Notes: Reproduced on AMO-dev with FF59, Win10x64

**Comment by EnTeQuAk** [comment] 2018-03-19 13:45
>     the linter detects no errors when certain properties are misspelled, for example:theme, headerURL, additional_backgrounds, colors, accentcolor, textcoloretc. - all these can be misspelled

That's a great idea to implement but not a bug but rather a nice enhancement we should implement at some point.

>    missing headerURL- the linter does not detect it - after clicking on 'Continue" an internal server error is generated
>    no error detected when an image is missing its extension, i.e..png, .svg -> internal server error generated after clicking Continue

@eviljeff should know more about this but that sounds like a addons-server bug to me?

>     no error detected when additional_backgrounds are defined but there is no additional_backgrounds_alignment property included or when additional_backgrounds_alignment does not specify a value for all the defined backgrounds

I think that's out of scope, still a nice enhancement but very low priority.

    accentcolor and textcolor - no error when value is an empty string ie. "" or when they contain a wrong color value (i.e. any value is accepted, like dje757$%#, 4)

That's a bug too imho, we should improve this. Depends on how Firefox handles this though.

>     when an image defined in the manifest is missing from the package - no error detected in the linter - after clicking on 'Continue" an internal server error is generated (similar to point 3)
 
I think that's the same error, cc @eviljeff on this.

**Comment by eviljeff** [comment] 2018-03-19 14:09
> no error detected when additional_backgrounds are defined but there is no additional_backgrounds_alignment property included or when additional_backgrounds_alignment does not specify a value for all the defined backgrounds

This isn't a fail - `additional_backgrounds_alignment` and `additional_backgrounds_tiling` are optional fields even if you specify `additional_backgrounds` and there isn't a requirement to specify a value for every `additional_background` either.

**Comment by eviljeff** [comment] 2018-03-19 14:28
logged mozilla/addons-server#7844 for the addons-server related bugs - not sure if there's anything else you want to handle in the linter to keep this issue open?

**Comment by AlexandraMoga** [comment] 2018-03-22 15:56
@EnTeQuAk I can log a separate issue related to color codes detection, but I'm not sure how you want to handle the rest (not server related) points.
Thanks

**Comment by EnTeQuAk** [comment] 2018-04-03 09:34
I filed #1945 and #1944 to handle these bugs separately, the rest has been reported in addons-server.

I'm closing this issue and everything else will be handled in specific issues.

**Closed by EnTeQuAk** 2018-04-03 09:34 UTC
