### ISSUE TITLE
Check that icons are valid image files

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-linter#1328] opened 2017-06-07 19:25 UTC
We should try to validate that the image is valid, to avoid getting broken images in Firefox.

**Comment by muffinresearch** [comment] 2017-06-07 19:30
Duplicate of https://github.com/mozilla/addons-linter/issues/1026

**Comment by muffinresearch** [comment] 2017-06-07 19:35
Ah looks like you're just splitting things up. As you were.

**Comment by ravneette** [comment] 2017-09-21 11:32
Hi @muffinresearch 

I would like to work on this. From what I could get it means that we need to validate if the icon is a valid image? So we need to verify if its extension is one of jpg, png or svg? 

Or does this issue also comprise of validating the size of the input image?

Also I see some work done on validation of image size here : https://github.com/mstriemer/addons-linter/commit/5cbdaaeed8edabb43efff20ca256a6199b003cd1

So should I contribute directly to @mstriemer's fork from this point, or should I file for a separate patch forked from master?

**Comment by EnTeQuAk** [comment] 2017-09-22 09:48
I answered a few of these questions in https://github.com/mozilla/addons-linter/pull/1558 directly, somehow I never submitted my comment here 😇

**Comment by muffinresearch** [comment] 2017-09-22 09:58
Hi @ravneette - I've marked this contrib assigned. I think @EnTeQuAk has covered what you were asking. Please let us know if you have any further questions.

**Comment by muffinresearch** [comment] 2017-09-22 10:15
Cross referencing the other issues I think it might be good to look at the magic number signature [1] of the file and check that with the supplied extension. 

That won't check that an image is corrupt but could help detect unexpected files.

[1] https://en.wikipedia.org/wiki/List_of_file_signatures

**Comment by muffinresearch** [comment] 2017-09-22 10:45
Checking magic numbers can definitely be split out into a separate issue/patch too.

**Closed** 2017-09-28 05:18 UTC
Labels: component: icons, component: schema, priority: enhancement, state: pull request ready, triaged

**Comment by ValentinaPC** [comment] 2017-09-28 07:00
Please add some STR for us to check this or the label "qa: not needed".
Thanks!
