### ISSUE TITLE
Validator is missing issues

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-linter#1473] opened 2017-08-16 14:27 UTC
ref: `https://addons.mozilla.org/editors/review/843980/`

Today I noticed that the following showed all passed (zero warnings)

`https://addons.mozilla.org/en-US/developers/addon/whaleslide_v1/file/702610/validation`

However there are multitude of issues that it should have listed.
For example, addons has an unrecognised JQuery which usually attracts a lot of warnings ( innerHTML etc).

Here is an example of warnings from an unrecognised JQuery:
`https://addons.mozilla.org/en-US/developers/addon/samo-select/file/702365/validation`

**Comment by wagnerand** [comment] 2017-08-16 15:08
That linked example uses a different jQuery file.

I'm not sure how actionable this issue is unless you can tell us exactly what pattern in what line of what file has been missed.

**Comment by erosman** [comment] 2017-08-16 15:24
Looking at an unrecognised jQuery v2.1.4, typical unrecognised JQuery warnings are: 

> eval can be harmful
> Unsafe assignment to innerHTML (multiple)

Looking at the addon in question, it has an unrecognised jQuery v2.1.1 (custom built)
It has 6 `innerHTML` (pretty identical/close to v2.1.4) that should have been picked up.

It also has `createElement("script")` but all of them do and they are not picked up validator at all.

**Comment by EnTeQuAk** [comment] 2017-09-25 08:27
This is a duplicate of https://github.com/mozilla/addons-linter/issues/1273 and should be fixed once this happens if it's not already fixed. Let's keep it open though to verify later.

**Comment by muffinresearch** [comment] 2019-06-14 14:32
This has mostly been dealt with due to Jquery updates and #1273 should cover anything else.

**Closed by muffinresearch** 2019-06-14 14:32 UTC
Labels: priority: p3, triaged
