### ISSUE TITLE
Fails on nullish coalescing operator

### ISSUE THREAD

**Issue by TheUnlocked** [mozilla/addons-linter#3154] opened 2020-05-04 23:16 UTC
### Describe the problem and steps to reproduce it:

Use the nullish coalescing operator `??` in a file and try to lint it.

Minimal repro:
```js
let x = undefined ?? "";
```

### What happened?

The linter reported a generic syntax error.

### What did you expect to happen?

No error.

### Anything else we should know?

The linter reports the error as occurring at line 1, col 1 despite the error being caused by the operator.

**Comment by Rob--W** [comment] 2020-05-05 10:48
Duplicate of #2978

**Comment by Rob--W** [comment] 2020-05-05 10:49
Sorry, edited the wrong issue. Still related though: this error is because the new syntax is not yet supported by eslint.

**Comment by willdurand** [comment] 2020-06-23 13:45
This is probably fixed by https://github.com/mozilla/addons-linter/pull/3161

**Closed by willdurand** 2020-06-23 13:45 UTC
