### ISSUE TITLE
Nullish coalescing operator (??)

### ISSUE THREAD

**Issue by jasonsavard** [mozilla/addons-linter#3226] opened 2020-06-27 15:22 UTC
### Describe the problem and steps to reproduce it:

This line of code failed probably due to the new Nullish Coalescing operator "??"

element.setAttribute("selected", await storage.get("key") ?? "");

### What happened?

JavaScript syntax error
Error: There is a JavaScript syntax error in your code; validation cannot continue on this file.
js/common.js line 1492 column 62

### What did you expect to happen?

Should pass linter

**Comment by willdurand** [comment] 2020-06-29 19:30
duplicate of https://github.com/mozilla/addons-linter/issues/3154

**Closed by willdurand** 2020-06-29 19:30 UTC
