### ISSUE TITLE
Clean out unnecessary add-ons code 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-linter#401] opened 2015-12-15 14:47 UTC
Give the focus on web extensions going forward we should clear out any un-used code. It'll still be there in the history for later on should we need it.

**Comment by EnTeQuAk** [comment] 2017-03-27 10:57
I feel like this is a dupe of https://github.com/mozilla/addons-linter/issues/1063, closing as such.

**Closed by EnTeQuAk** 2017-03-27 10:57 UTC
Labels: component: code quality, triaged
