### ISSUE TITLE
Add a lint warning when both applications.gecko and browser_specific_settings.gecko are being used in the same manifest.json file

### ISSUE THREAD

**Issue by rpl** [mozilla/addons-linter#2294] opened 2018-11-27 13:44 UTC
As part of #2285, the addons-linter is going to use the `"browser_specific_settings"` manifest property as an alias of the `"applications"` manifest property when `"browser_specific_settings"` contains a `"gecko"` property.

As a follow up of this new behavior, the addons-linter should log a linting warning when both `"browser_specific_settings"` and `"applications"` have a `"gecko"` property in the same manifest.json file
(see https://github.com/mozilla/addons-linter/pull/2285#discussion_r235926818 for a rationale)

**Comment by andreeaNeamtiu** [comment] 2020-02-14 16:10
I started working on this:)

**Comment by rpl** [comment] 2020-02-17 17:21
@andreeaNeamtiu Great! feel free to ask more details if needed or if you get stuck.

**Comment by Yrkan** [comment] 2020-10-26 20:20
@rpl Is this issue still valid ? if so i would love to work on it.

**Comment by rpl** [comment] 2020-10-27 12:27
> @rpl Is this issue still valid ? if so i would love to work on it.

Yes, this issue still look valid.

First step of working on this should actually be to verify that by yourself (because that makes you sure that you have got a good picture of the issue and you know how to reproduce it, and then you can try again after you are starting to make changes and verify what results you get):
- create a minimal test extension
- add both `applications` and `browser_specific_settings` properties to the manifest.json file of the minimal extension
- run the addons-linter on the minimal extension and verify that no warning is being reported for the issue yet

If you have never wrote an extension before, you may want to take a look to the following doc pages:
- https://extensionworkshop.com/documentation/develop/ (and also the "Build an extension in 5 minutes" intro if this is the first extension that you are writing)
- MDN API doc references for the manifest.json keys supported: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json
- The mdn/webextensions-examples repository includes a lot of small minimal example extensions: https://github.com/mdn/webextensions-examples

The changes needed to fix this issue should likely be applied in `src/parsers/manifestjson.js`, and a new test case should be added to `tests/unit/parsers/test.manifestjson.js`.

**Comment by Yrkan** [comment] 2020-10-27 14:37
@rpl Oh i got it, i was confused because i didn't know about "applications" key before but it appears to be the same as "browser_specific_settings".
I did reproduce the issue and made a patch to fix it, i'll open a PR right now. yet i'm a bit concerned  about the message code and description i feel they could be better.

**Comment by wagnerand** [comment] 2020-10-27 14:40
@rpl Hm, shouldn't we already warn when both `"browser_specific_settings"` and `"applications"`are defined in manifest.json?

**Comment by rpl** [comment] 2020-10-27 15:20
> @rpl Hm, shouldn't we already warn when both `"browser_specific_settings"` and `"applications"` are defined in manifest.json?

@wagnerand 
I looked to the related code and it doesn't seem we do at the moment, we do overwrite `applications` with `browser_specific_settings` here to use them as aliases of each other here: https://github.com/mozilla/addons-linter/blob/ab124e835dfba772f67341b5e4d7107a7095c644/src/parsers/manifestjson.js#L306-L311

I haven't tried to reproduce it locally, but based on https://github.com/mozilla/addons-linter/issues/2294#issuecomment-717288850 it seems that @yrkan have tried and verified that no warning is collected for this.

have you tried to run the addons-linter released version on a small test extension with both `"browser_specific_settings"` and `"applications"` and got a warning?
I wouldn't exclude that we may be checking that also elsewhere and not on the linter side yet, e.g. some other checks done on the addons-server side, is that the case?

**Comment by Yrkan** [comment] 2020-10-27 15:37
@rpl i can confirm that with the latest build of addons-linter there is not warning if both `"browser_specific_settings" ` and `"applications"`are used.
![image](https://user-images.githubusercontent.com/29315771/97324722-739dec80-1872-11eb-9591-cae606bfce8d.png)

**Comment by wagnerand** [comment] 2020-10-27 15:38
@rpl Sorry, that was not what I meant.

I was suggesting that the fix for this issue is that we warn when both "browser_specific_settings" and "applications" are defined in manifest.json (and ignore whether `gecko` is defined in either or both).

**Comment by rpl** [comment] 2020-10-27 15:52
> @rpl Sorry, that was not what I meant.
> 
> I was suggesting that the fix for this issue is that we warn when both `"browser_specific_settings"` and `"applications"` are defined in manifest.json (and ignore whether `"gecko"` is defined in either or both).

ah, sorry I definitely misunderstood what you meant.

For the purpose of the warning what you are suggesting sounds definitely reasonable, we should warn if the manifest have both the properties (independently from what they actual contains).

Another scenario that we may want to consider is:
- an extension does have both and their "gecko" properties contains different content.

In that case it may be more reasonable to record a blocking validation error.
 
@wagnerand how that sounds to you?

**Comment by wagnerand** [comment] 2020-10-27 15:58
> 
> Another scenario that we may want to consider is:
> 
>     * an extension does have both and their "gecko" properties contains different content.
> 
> 
> In that case it may be more reasonable to record a blocking validation error.
> 
> @wagnerand how that sounds to you?

@rpl I was first considering we might want to error in all cases, but that's probably a bit too strict.

I assume there is defined and consistent/reproducible behavior which of `"browser_specific_settings"` and `"applications"` takes precedence if both are defined. If there is, we might not have to error though. In that case, we could make that a warning and even lower the more general case to an info, saying that the property is going to be ignored.

**Comment by rpl** [comment] 2020-10-27 16:11
> @rpl I was first considering we might want to error in all cases, but that's probably a bit too strict.
> 
> I assume there is defined and consistent/reproducible behavior which of `"browser_specific_settings"` and `"applications"` takes precedence if both are defined. If there is, we might not have to error though. In that case, we could make that a warning and even lower the more general case to an info, saying that the property is going to be ignored.

@wagnerand yes, `"browser_specific_settings"` is the one that takes precedence (on Firefox, and then we kept the same convention also here in the addons-linter and in web-ext).

I was mainly thinking of collecting an error when their content differs because it may trigger issues that may surprise the developers if they at some point remove `"browser_specific_settings"` and `"applications"` contains a different `"id" for the extension (or different compatibility ranges or update url).

**Comment by wagnerand** [comment] 2020-10-27 16:58
> @wagnerand yes, `"browser_specific_settings"` is the one that takes precedence (on Firefox, and then we kept the same convention also here in the addons-linter and in web-ext).
> 
> I was mainly thinking of collecting an error when their content differs because it may trigger issues that may surprise the developers if they at some point remove `"browser_specific_settings"` and `"applications"` contains a different `"id" for the extension (or different compatibility ranges or update url).

Ah cool. I am not opposed to issuing an error. I was thinking throwing a warning would be more consistent here because we usually throw errors only when that file would not work (or severely break) in Firefox.

**Comment by Yrkan** [comment] 2020-10-27 19:41
**This PR will be changed according to the final decision**

**Closed** 2020-10-30 14:38 UTC
Labels: component: rule, contrib: welcome, priority: p3
