### ISSUE TITLE
"Icons must be square." for svg icons

### ISSUE THREAD

**Issue by lilydjwg** [mozilla/addons-linter#3322] opened 2020-09-07 11:22 UTC
### Describe the problem and steps to reproduce it:

I'm trying to upload a new version of [cf-pop](https://addons.mozilla.org/firefox/addon/cf-pop/) to amo.

### What happened?

It says `Icons must be square.` and `Icon at "icons/Cloudflare-gray.svg" must be square.` twice.

### What did you expect to happen?

It should accept svg icons (like before).

### Anything else we should know?

The icon file didn't change. It's exactly the same icon file in the published version.

**Comment by Rob--W** [comment] 2020-09-07 11:57
This should have been a warning, not an error:
https://github.com/mozilla/addons-linter/blob/7530c81c27e7d8484b7d76381924489eaf07a5b3/src/parsers/manifestjson.js#L497

**Comment by lilydjwg** [comment] 2020-09-07 12:29
But what I see on the website is an error and I can't continue (the button to continue is gray).

**Comment by Rob--W** [comment] 2020-09-17 13:06
Mentor: @rpl

**Comment by parasgoyal12** [comment] 2020-09-20 10:30
Hello Sir,
I am interested in this. Kindly help me get started.

Regards

**Comment by Yashs911** [comment] 2020-10-09 15:13
Hi, @rpl I would like to work on this issue.

**Comment by rpl** [comment] 2020-10-09 15:40
@Yashs911 welcome! feel free to look into it and create a pull request (the issue will be marked as `contrib: assigned` once a pull request has been created).

In https://github.com/mozilla/addons-linter/issues/3322#issuecomment-688277745 Rob did point out which part of the addons-linter source code you may have to look into and apply some changes to.

This repository's README.md file contains some informations about the addons-linter architecture, how to run tests etc.
I'd suggest to start by:
- giving a look to the README.md, then try to run the tests without apply any changes yet (just to be sure that your development environment is correctly configured)
- then try to reproduce the issue described in this issue (and ask some questions if needed, e.g. if you are not able to reproduce it or to fully get what is wrong and what should happen instead) 
- then start to look to the code that Rob did point to (and then look to the surrounding code to get a more detailed picture about how that part of the architecture works) and finally try to apply the needed changes

Let us know if you have any other doubts or if you get stuck on some of this steps.

**Comment by Yashs911** [comment] 2020-10-09 16:07
@rpl few tests failed after I ran npm run test how to fix them and how to reproduce the error?

![fail](https://user-images.githubusercontent.com/64412143/95605945-492cf080-0a77-11eb-9333-7e9aa1d4ad58.JPG)

**Comment by rpl** [comment] 2020-10-09 16:21
> @rpl few tests failed after I ran npm run test how to fix them and how to reproduce the error?

are you running the tests on windows?
it may be due to some OS differences when running the tests on windows, I don't have a windows box nearby to me at the moment, but I can give it a try over the weekend.

Another option may be to try to use WSL and run the tests from there.

To reproduce the issue you can create a simple test extension (e.g. you may use `npx create-webextension an-extension-dir-name` to create a simple basic extension and then tweak to reproduce the issue), and then set the extension icon in the manifest to a non square svg file (see also the following doc page https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/icons) and then execute the addons-linter on it (`./bin/addons-linter path-to-extension-dir`).

**Comment by imabp** [comment] 2020-10-09 21:36
I would like to work on it. Can you help me out @rpl

**Comment by erolaliyev** [comment] 2020-10-13 11:55
Hi, @Yashs911 , are you still working on this issue? I would like to work on it if you aren't. Thank you.

**Comment by rpl** [comment] 2020-10-13 12:44
@Yashs911 I confirm you that those are legit issue with running the addons-linter tests on a windows native shell (I tried on powershell but I'm pretty sure that the same would happen with cmd). To make the addons-linter test suite able to work natively on windows we'll need to fix those issues, separately from fixing this one.

In the meantime you could use Windows WSL to run the tests into an Ubuntu-based environment, I verified that on WSL the test suite does work as it does natively on Linux or in the travis CI jobs. 

As a side note about working on this repo from WSL:

Don't use a git clone that you may have already created on windows, `npm run test-once` seems to get stuck when running from WSL on a git clone created from windows (may be due to the way accessing to the windows files is abstracted in WSL) 

You have to git clone it from inside a WSL linux shell, and in that git clone you can then run `npm ci`, `npm run build` and `npm run test` successfully from inside WSL.

You may install nvm inside WSL to make it easier to get an updated nodejs version: https://github.com/nvm-sh/nvm#install--update-script

**Comment by Yashs911** [comment] 2020-10-13 14:31
@rpl thanks for the information I will need to set up WSL first and I guess that will help me in future open contribution.

**Comment by ThamiMemel** [comment] 2020-10-16 23:43
Hello i use Linux and i manage to reproduce the error, i changed it to a warning, i'll make a PR please correct me if i'm wrong or i misunderstood the issue this is my first contrib.
thanks.

**Closed** 2020-10-26 10:07 UTC
Labels: contrib: good first bug, contrib: mentor assigned
